name: surveyportal
recipe: platformsh
config:
  id: ogjymcrf4mzra
services:
  app:
    overrides:
      environment:
        COMPOSER_MEMORY_LIMIT: -1
tooling:
  drush:
    service: app
    cmd: drush
  composer:
    service: app
    cmd: composer
