<?php

/**
 * @file
 * Contains shc_tweaks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;



/**
 * Implements hook_help().
 */
function shc_tweaks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the shc_tweaks module.
    case 'help.page.shc_tweaks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Various tweaks and overrides for the StrongHealthyCommunities survey portal') . '</p>';
      return $output;

    default:
  }
}

/**
 * hook_form_FORM_ID_alter().
 */
function shc_tweaks_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  unset($form['meta']);
  unset($form['menu']);
  unset($form['path']);
  unset($form['author']);
  unset($form['options']);
}


