<?php

/**
 * @file
 * Contains shc_migrate_change_club.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 */
function shc_migrate_change_club_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the shc_migrate_change_club module.
    case 'help.page.shc_migrate_change_club':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrates survey responses from Qualtrics to create/update users and nodes of type change_club') . '</p>';
      return $output;

    default:
  }
}



/**
 * Downloads survey results from qualtrics().
 */
function shc_migrate_change_club_runner(){
// get settings
  $config = \Drupal::config("shc_migrate_change_club.credentials");
  $settings = array();
  $settings["survey_id"] = $config->get("survey_id");
  $surveys = explode("|", $settings["survey_id"]);
  $survey ="";
  $index = 0;
  foreach($surveys as $survey) {
    // Use $key as an index, or...

    // ... manage the index this way..
    echo "Index is ".$index."<br>";
    echo $surveys[$index]."<br>";
    $textout = shc_migrate_change_club_post_qualtrics($surveys[$index]);
    echo $textout."<br>";
    $index++;
  }

  //$surveyid = $surveys[0];
  //return shc_migrate_change_club_post_qualtrics($surveyid);
}


/**
 * Downloads survey results from qualtrics().
 */
function shc_migrate_change_club_post_qualtrics($surveyid){
  $progressid = "";
  $fileid = "";
  $filedownload = "";

// get settings
  $config = \Drupal::config("shc_migrate_change_club.credentials");
  $settings = array();
  $settings["api_token"] = $config->get("api_token");
  $settings["data_center"] = $config->get("data_center");
//get a session ID
  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://".$settings['data_center'].".qualtrics.com/API/v3/surveys/".$surveyid."/export-responses",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_POSTFIELDS =>"{\n\t\"format\": \"json\"\n}",
    CURLOPT_HTTPHEADER => array(
      "X-API-TOKEN: ".$settings['api_token'],
      "Content-Type: application/json"
    ),
  ));

  $progressid = curl_exec($curl);

  curl_close($curl);
  $progressid = json_decode($progressid);
    if (!empty($progressid->result->progressId)){
    $progressid =  $progressid->result->progressId;
    }else{
      echo "No progressid! ";
    }
// get a file ID
  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://".$settings['data_center'].".qualtrics.com/API/v3/surveys/".$surveyid."/export-responses/".$progressid."",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_HTTPHEADER => array(
      "X-API-TOKEN: ".$settings['api_token'],
      "Content-Type: application/json"
    ),
  ));

  $fileid = curl_exec($curl);

  curl_close($curl);
  $fileid = json_decode($fileid);
    if (!empty($fileid->result->fileId)){
      $fileid =  $fileid->result->fileId;
    }else{
      echo "No file ID !";
    }
// download and save the .zip file
// file to save the contents to
  $fp = fopen("../private/qualtrics_data/".$surveyid.".zip", "w+b");
  $curl = curl_init();
  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://".$settings['data_center'].".qualtrics.com/API/v3/surveys/".$surveyid."/export-responses/".$fileid."/file",
    CURLOPT_FILE => $fp,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_HTTPHEADER => array(
      "X-API-TOKEN: ".$settings['api_token'],
      "Content-Type: application/json"
    ),
  ));

  $filedownload = curl_exec($curl);
    if (!empty($filedownload)){
      fwrite($fp, $filedownload);
      $textout = "File Downloaded! ";

    }else{
      echo "File Download failed! ";
    }

  curl_close($curl);
  fclose($fp);
  $textout = $textout . shc_migrate_change_club_unzip($surveyid);
  //shc_migrate_change_club_rename();
  return $textout;

}


/**
 * Unzips and renames file downloaded from qualtrics().
 */
function shc_migrate_change_club_unzip($surveyid){

// zip file name
$filename = '../private/qualtrics_data/'.$surveyid.'.zip';
// unzip path
$path = "../private/qualtrics_data/";
// do the business
$zip = new ZipArchive;
$res = $zip->open($filename);
  if ($res === TRUE) {
  // get file name, only one name
   $oldname = $zip->getNameIndex(0);
  // rename file
   $zip->renameName($oldname, $surveyid.'.json');
   $zip->close();
   $textout = 'Renamed! ';
  } else {
   $textout = 'Rename failed! ';
  }
$res = $zip->open($filename);
  if ($res === TRUE) {
   // extract file
   $zip->extractTo($path);
   $zip->close();
   $textout = $textout . 'Unzipped! ';
  } else {
   $textout = $textout . 'Unzip failed! ';
  }

return $textout;

}



function shc_migrate_change_club_post_qualtricssession($settings){

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://".$settings['data_center'].".qualtrics.com/API/v3/surveys/".$settings['survey_id']."/export-responses",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS =>"{\n\t\"format\": \"json\"\n}",
  CURLOPT_HTTPHEADER => array(
    "X-API-TOKEN: ".$settings['api_token'],
    "Content-Type: application/json"
  ),
));

$response = curl_exec($curl);

curl_close($curl);
$response = json_decode($response);
$response =  $response->result->progressId;
return $response;


}

function shc_migrate_change_club_get_qualtricsfileid($settings, $progressid){

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://".$settings['data_center'].".qualtrics.com/API/v3/surveys/".$settings['survey_id']."/export-responses/".$progressid."",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "X-API-TOKEN: ".$settings['api_token'],
    "Content-Type: application/json"
  ),
));

$response = curl_exec($curl);

curl_close($curl);
$response = json_decode($response);
$response =  $response->result->fileId;
return $response;


}


function shc_migrate_change_club_get_qualtricsfile($settings, $fileid){

// Directory to save qualtrics data exports
$directory = 'private://qualtrics_data';
// File to save the contents to
//$fp = fopen(''.$directory.'/'.$settings['survey_id'].'.zip', 'w+');
$curl = curl_init();
$fp = fopen("../private/qualtrics_data/".$settings['survey_id'].".zip", "w+b");
curl_setopt_array($curl, array(
  CURLOPT_URL => "https://".$settings['data_center'].".qualtrics.com/API/v3/surveys/".$settings['survey_id']."/export-responses/".$fileid."/file",
  CURLOPT_FILE => $fp,
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "X-API-TOKEN: ".$settings['api_token'],
    "Content-Type: application/json"
  ),
));

$response = curl_exec($curl);
echo $response;
fwrite($fp,$response);
curl_close($curl);
fclose($fp);



}


/**
 * Implements hook_theme().
 */
function shc_migrate_change_club_theme() {
  return [
    'default_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
